import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '100%',
    backgroundColor: '#111622',
    paddingHorizontal: 40,
  },
  header: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 48,
    fontWeight: 'bold',
    fontFamily: 'Menlo',
    textTransform: 'uppercase',
    letterSpacing: -4,
    lineHeight: 50,
    color: '#e1e1e1',
    transform: [
      {
        scaleY: 1.75,
      },
    ],
  },
  body: {
    width: '100%',
    flex: 3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  powerButtonContainer: {
    width: 200,
    height: 200,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2cb68c',
    shadowColor: '#2cb68c',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    borderWidth: 4,
    borderColor: '#5cd7b2',
    borderRadius: 9999,
  },
  powerOnButton: {
    width: 200,
    height: 200,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9999,
    overflow: 'hidden',
  },
  footer: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  devicesButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#19212b',
    shadowColor: '#393e47',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    borderColor: '#393e47',
    borderWidth: 2,
    borderRadius: 10,
    padding: 14,
  },
  buttonText: {
    color: '#e1e1e1',
    fontSize: 20,
  },
});
